### ISSUE TITLE
splitting test-work for milestone 1

### ISSUE THREAD

**Issue by akleefel** [UBC-MDS/ezmodel#4]
The following people will write the tests for these functions: 

* Sean: regularization_plot(), coerce()
* Tyler: score()
* Alex: test_train_plot()

**Comment by tylercroberts** [comment]
### Tests added for `Score()`:

##### Tests for `__init__()`
* `test_setters_no_data()`
> Ensure that attributes are being assigned as expected.

* `test_input_exceptions_no_data()`
> Ensure exceptions are thrown when they are expected to be

* `test_setters()`
> Ensure that attributes are being assigned as expected.

* `test_input_exceptions()`
> Ensure exceptions are thrown when they are expected to be

##### Tests for output results.
* `test_outputs_str()`
 > Type checks the output of a single score_type, and ensures `mse` is being computed correctly.

* `test_outputs_list()`
>Type checks the output of a list of score_types, and ensures `mse`  and 'accuracy' are being computed correctly.
